# Generated by Django 5.2.8 on 2025-11-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='edad',
            field=models.CharField(default=30, max_length=100),
            preserve_default=False,
        ),
    ]
