# Generated by Django 5.2.8 on 2025-11-26 03:43

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_autor_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='nombre',
            field=models.CharField(max_length=100, validators=[biblioteca.models.validar_nombre]),
        ),
    ]
