# Generated by Django 5.2.8 on 2025-11-26 03:48

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_autor_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='resumen',
            field=models.TextField(validators=[biblioteca.models.validar_resumen]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='calificacion',
            field=models.IntegerField(validators=[biblioteca.models.validar_resena]),
        ),
    ]
